### ISSUE TITLE
Survey Checklist

### ISSUE THREAD

**Issue by kgilds** [kgilds/kevinsblogIII#2]
- [x] council
- [x] back button 
- [x] header
- [x] footer
- [x] sites
- [x] test site/grant
- [x] test grade level
- [x] sites in order by council
- [x] site display logic tested
- [x] display logic for troop number tested
- [x] girl code
- [x] embeded girl code
- [x] scales
- [x] scoring
- [x] labels
- [] end of survey process
- [x] link shared
- [x] launched
